# Generated by Django 4.1.3 on 2022-11-25 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hook_text',
        ),
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
