# Generated by Django 3.2 on 2022-12-01 03:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_post_sc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
