# Generated by Django 3.2 on 2022-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
