# Generated by Django 3.2 on 2022-12-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0008_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sc_image',
        ),
    ]
