# Generated by Django 3.2 on 2022-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0009_remove_post_sc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_content',
            field=models.TextField(blank=True),
        ),
    ]
