# Generated by Django 3.2 on 2022-12-01 13:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0010_post_img_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
