# Generated by Django 3.2 on 2022-12-01 14:41

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0011_auto_20221201_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
