# Generated by Django 3.2 on 2022-12-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0013_auto_20221201_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_content',
            new_name='images',
        ),
    ]
