# Generated by Django 3.2 on 2022-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_post_updated_at_alter_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='raffle/images/%Y/%m/%d/'),
        ),
    ]
