# Generated by Django 3.2 on 2022-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.TextField(blank=True),
        ),
    ]
